### ISSUE TITLE
mastodon.errors.MastodonNetworkError: Could not connect to streaming server: Unauthorized

### ISSUE THREAD

**Issue by mneedham** [saubury/mastodon-stream#1]
I was trying this out by running the Mastadon listener:

```
python mastodonlisten.py --baseURL https://mastodon.social --enableKafka
```

But it always tells me I'm unauthorized. 

```
Traceback (most recent call last):
  File "/Users/markhneedham/projects/mastodon-stream/mastodonlisten.py", line 161, in <module>
    main()
  File "/Users/markhneedham/projects/mastodon-stream/mastodonlisten.py", line 158, in main
    mastodon.stream_local(Listener())
  File "/Users/markhneedham/projects/mastodon-stream/env/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/markhneedham/projects/mastodon-stream/env/lib/python3.11/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/markhneedham/projects/mastodon-stream/env/lib/python3.11/site-packages/mastodon/streaming_endpoints.py", line 34, in stream_local
    return self.__stream('/api/v1/streaming/public/local', listener, run_async=run_async, timeout=timeout, reconnect_async=reconnect_async, reconnect_async_wait_sec=reconnect_async_wait_sec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/markhneedham/projects/mastodon-stream/env/lib/python3.11/site-packages/mastodon/internals.py", line 542, in __stream
    connection = connect_func()
                 ^^^^^^^^^^^^^^
  File "/Users/markhneedham/projects/mastodon-stream/env/lib/python3.11/site-packages/mastodon/internals.py", line 447, in connect_func
    raise MastodonNetworkError(
mastodon.errors.MastodonNetworkError: Could not connect to streaming server: Unauthorized
```

Do I need to pass in some credentials or something?

**Comment by saubury** [comment]
Hi @mneedham 

Thanks for trying out the project. _Generally_, you don't need your python application to be authorized to listen to a mastodon feed. However, it looks like mastodon.social has changed something. To have a look at another example, try this (which should work without authorization)

`python mastodonlisten.py --baseURL https://aus.social --public`

The [docs](https://mastodonpy.readthedocs.io/en/stable/01_general.html) actually recommend to _not_ authenticate so the server knows to rate limit the application

_If your application requires many hits to endpoints that are available without logging in, do consider using Mastodon.py without authenticating to get the full per-IP limit_

I may look to add an optional authorization step for the servers that look like they need it
